- name: Get cluster ip addresses
  set_fact:
    cluster_ip_addresses: "{{ cluster_ip_addresses }} + [ '{{ hostvars[item].ansible_facts.all_ipv4_addresses[0] }}' ]"
  with_items: 
    "{{ groups.aerospike_cluster }}"
  vars:
      cluster_ip_addresses: []

- debug:
    msg: " {{ cluster_ip_addresses[0] }}"

- name: Get heartbeat ip addresses
  set_fact:
    heart_beat_ip_addresses: "{{ heart_beat_ip_addresses }} + [ '{{ item }}' ]"
  with_items: 
    "{{ aerospike_heartbeat_ips }}"
  vars:
      heart_beat_ip_addresses: []

- name: Get data center ip addresses
  set_fact:
    other_dc_ips: "{{ other_dc_ips }} + [ '{{ item }}' ]"
  with_items: 
    "{{ other_dc_ip_addresses }}"
  vars:
      other_dc_ips: []

- debug:
    msg: "{{ heart_beat_ip_addresses[0] }}"
    msg: "{{ heart_beat_ip_addresses[1] }}"

- name: "Get available nvme drives"
  shell:
    cmd: "ls /dev/sda2"
  register: nvme_drives_list_output
  
- name: "Get hostname"
  shell:
    cmd: "hostname -i"
  register: host_ip

- debug:
    msg: "{{ host_ip['stdout'] }}"

- name: Store nvme drive list as a fact
  set_fact: 
    nvme_devices : "{{ nvme_drives_list_output.stdout_lines }}"

- name: Copy configuration
  template:
    src: "assets/{{ aerospike_conf_file_name }}.j2"
    dest: "{{ conf_location }}/{{ aerospike_conf_file_name }}"
    mode: '0644'
    owner: root
    group: root
  vars:
    ip_address: "{{ hostvars[inventory_hostname].ansible_facts.all_ipv4_addresses[0] }}"    

- name: Copy python script to add heartbeat plane addresses
  template:
    src: "assets/replace_heartbeat_address.py"
    dest: "{{ conf_location }}/replace_heartbeat_address.py"
  vars:
    ip_address: "{{ hostvars[inventory_hostname].ansible_facts.all_ipv4_addresses[0] }}"    

- name: Copy License
  template:
    src: "assets/{{ feature_key_file_name }}.j2"
    dest: "{{ license_location }}/{{ feature_key_file_name }}"
    mode: '0644'
    owner: root
    group: root
  vars:
    ip_address: "{{ hostvars[inventory_hostname].ansible_facts.all_ipv4_addresses[0] }}"    


- block:
  - name: Make sure certificates & private key directories exist
    file: 
      path: "{{ item }}"
      state: directory    
      owner: root
      group: root
      mode: 0555
    with_items:
    - "{{ certs_location }}"

  - name: Copy certificates across
    copy: 
      src: "assets/certificates/certs/{{ item }}"
      dest: "{{ certs_location }}"
      owner: root
      group: root
      mode: 0444
    with_items:
    - ca.crt
    - server.crt

  - name: Copy private key across
    copy: 
      src: "assets/certificates/private/server.key"
      dest: "{{ certs_location }}"
      owner: root
      group: root
      mode: 0400

  when: tls_enabled         
